name: flutter_realtime
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  grpc: ^3.0.2
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2
  provider: ^6.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
